language: node_js
node_js:
- '5'
script:
- npm run lint
- npm test
deploy:
  provider: heroku
  app:
  	master: starship-react
  api_key:
    secure: WKyZJwEpQVPD6/Kzgpbrk8fY2FJCPCnkHU1r1r3L4+FuYAC7w3lc1KIPyXNP59nRPRMBg4Wsw9tJk7L/rep9YqI6AZyS4aWuvB6ze0acE23XW+EpJEmokFU2HUC3U92I96ude6M1eFeJkzHcOS/0yQuAGYxZtKITxh01ZFcwCug2IqbhyaeqHavPt6a7SR8ulUkZbjU63PV3J6D5Ypa1yeYbfH9w+kvL0wh7VrxqV0rk9IUR49frYC1P6MoYaZ5iLg1k0J7ldp8OqjvdR3vOLDF6NKxx4HSDEjWE4izC/HUtgrfVAhhK+L1nmfFPwHopHc5stAqjL4eo9xyUs4v3hp7NWh+vhBeL63ly6aDB9H/0cLZfGMJ5Iqv//KgOpXF5zsYv1nSkT6by4hOSDzCTpnXA2+15jquvHOzuD6Md6WSJBEuZwGzKKOc8EodzhmHF4Lzx+QDcQp4rbm6gioQIUEo1wqntLiEF37cnxNv9GiQ9UlD9dYHZYHqXS/ihcN0DpXG/zvfVJNxFdHgUJkuzlO9sCnOvGzY4tiDzSWEt869z2/fsWWnbA23kfFNqk9Ba+ePBviYGtcUt+ppLUQIvi44R41pN9aELVBJw3Vh4f1SfKqYLPXu8qB+oih9OkNuPjNVw7hAoOa8QGEFALjSpsykIbsQ2H7Rei8OoJNXGNH0=
